### ISSUE TITLE
Site lacks meta description

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/wp2030-microsite#137]
- `head` lacks `meta description`

**Comment by JessicaMarine1** [comment]
@brentryanjohnson are you able to help build out this ticket more and provide the suggested `meta description` were needed

**Comment by brentryanjohnson** [comment]
Pull requests #210 and #213 are for adding descriptions that can be used for `meta`. These are page-level, so (almost) every page should have one. Other work needed apart from those two PRs:
- Add meta description to `head` that pulls in page descriptions from front matter
- Add and use a global meta description for the homepage and pages that don't have a description

**Comment by mark-meyer** [comment]
@lesliel789 this should be on the [staging branch](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/) now.

User's shouldn't see any changes to the site with this. The only way to verify this is to look at the page source. If you _want_ to do that, you can:

- Go to a page (this assumes you're using Chrome)
- Right-click in the pages and select "View Page Source"
- You should see near the top the meta description tag that looks like:
    - `<meta name="description" content="Workplace is GSA’s effort to lead and support federal agencies through the return to office and the future of work.">`

**Comment by lesliel789** [comment]
@mark-meyer thank you for explaining that process! I checked it out for fun and I see the updated meta description. Thanks, I'll move ticket to done.
