### ISSUE TITLE
Link in NRC article

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#140]
On this page https://workplace.gsa.gov/insights/nrc-gsa-space-reduction-and-cost-savings-in-new-lease/
in the second paragraph please link to the workplace engagement offering:

"PBS and NRC partnered on a [workplace engagement](https://workplace.gsa.gov/offerings/workplace-engagements/) study that analyzed the NRC's space..."
(the link is https://workplace.gsa.gov/offerings/workplace-engagements/)

**Comment by JessicaMarine1** [comment]
@lesliel789 This is ready for your review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/JessicaMarine1-patch-3/insights/nrc-gsa-space-reduction-and-cost-savings-in-new-lease/

**Comment by lesliel789** [comment]
Reviewed and looks good. Ready to move forward - thanks!!
