### ISSUE TITLE
Links in Coworking articles

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#141]
- [ ] On this page https://workplace.gsa.gov/insights/commercial-coworking-pilot-lessons-learned/ 
in the very last sentence please link "commercial" and "federally owned" to two separate pages:

"Learn about GSA's coworking offerings in both [commercial ](https://workplace.gsa.gov/offerings/commercial-coworking/)and [federally owned](https://workplace.gsa.gov/offerings/) space."

Note: Commercial will continue to point to the Commercial Coworking offerings page, and until we get a Federal Coworking child page, that can point to the general Offerings page.

**Comment by mark-meyer** [comment]
Staging branch: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@lesliel789 Please review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by lesliel789** [comment]
Looking great!  The commercial coworking USGS article needs two changes
please.
The end quote is missing on Chuck's quote paragraph toward the bottom.
Also the very last paragraph of the story is missing. Below the text that
is already there please add:

“So far we are pleased, but it’s too soon to really tell on its overall use
as we're juggling now four different locations for over 90 staff – so we're
still figuring things out, but suspect we'll re-compete next year to
continue while we have no office or home base,” said Schuster.

Thanks!

**Comment by JessicaMarine1** [comment]
Adding these requested changes to #181
