### ISSUE TITLE
Links in Customer Collab article

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#142]
- [ ]  On this article page https://workplace.gsa.gov/insights/gsas-customer-collaboration-event-recap/ let's link the first four offerings bullets to their offering child pages please. 

- [ ] Also, please update the WIFM full name in the bullet to "Workplace Investment & Feasibility Modeling Tool"

**Comment by JessicaMarine1** [comment]
@lesliel789 This is ready for your review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/JessicaMarine1-patch-4/insights/gsas-customer-collaboration-event-recap/

**Comment by lesliel789** [comment]
Reviewed and looks good. Ready to move forward - thanks!!
