### ISSUE TITLE
WIL | Photo gallery (**to be launched 2/7**)

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/wp2030-microsite#143]
Consider not displaying all WIL photos on landing page, to alleviate some scrolling for users:

- [ ] Show only three thumbnail photos on the WIL page, and link to a separate page that displays all the photo thumbnails. 
- [ ] 3 photos for main WIL page are: Row 1 column 3 (two grey chairs in a nook); row 3 column 3 (inside view of blue/green room); people in hall (https://drive.google.com/file/d/1eyEos5SPQjkVdnYA1TSGoSXw6Xzk48Kv/view?usp=share_link)
- [ ] Below the three images on the main WIL page, let's have this text: "View the full gallery" that links to the gallery page 
- [ ] On that separate gallery page, clicking on a photo will open up a slideshow, just like the existing slideshow.
- [ ] Let's have text on that page: "~~Click on any~~ Select an image to open a slideshow."
- [ ] Edits to photos in gallery:
   - [ ]  **Delete** the one with the Miller Knoll vendor banner
   - [ ]  **Add** all the photos in this folder:
https://drive.google.com/drive/folders/1Tol72vVHOm70ol5u4gATEMvxqUSglSVk?usp=sharing

**Comment by lesliel789** [comment]
@vickimcfadden and @actuallyjenn  I'd like to revisit our options for this gallery please. And hopefully make gallery changes on 2/7 along with the other WIL page changes tomorrow (plan A content with link and add video) please. 

I like three pictures showing on the WIL page and users can either click a link to a full gallery on a new page or can arrow forward and back on the WIL page like a carousel. 
Which is most feasible by tomorrow please? Or is there a better idea?

Also I'll be selecting specific photos for the gallery and linking them in this ticket prior to moving it to "ready."
Thanks!
@JessicaMarine1 FYSA

**Comment by lesliel789** [comment]
The photos currently in the gallery are all good, except please delete the one with the Miller Knoll vendor banner. 
And please add all the photos in this folder to the gallery:
https://drive.google.com/drive/folders/1Tol72vVHOm70ol5u4gATEMvxqUSglSVk?usp=sharing

**Comment by jfredrickson5** [comment]
@lesliel789 I'm not sure about implementing a carousel right on the page, but we could do either:

* The first method you suggested, which is to show only three thumbnail photos on the WIL page, and link to a separate page that displays all the photo thumbnails. On that separate page, clicking on a photo will open up a slideshow, just like the existing slideshow.

* Show three thumbnail photos on the WIL page, but don't link to a separate page for the gallery. Instead, clicking on one of those three photos will bring up the full slideshow containing all photos.

**Comment by lesliel789** [comment]
@jfredrickson5 thanks for the info and ideas!
Lets' go with option 1 please (have a gallery page). Let's have text on that page: "Click on any image to open a slideshow." 
On the WIL page View photo gallery section, below the three images, let's have this text: "View the full gallery" that links to the gallery page please.

**Comment by JessicaMarine1** [comment]
@lesliel789 Do you have a preference for which 3 photos are on the main WIL page?

**Comment by JessicaMarine1** [comment]
@jfredrickson5 @lesliel789 I updated the issue to include all the instruction / decisions made in the thread. Just need @lesliel789 to ID which 3 pics she wants on mail WIL page (if it matters)

**Comment by JessicaMarine1** [comment]
@jfredrickson5 Leslie and I met and this one is ready to be worked! ty

**Comment by JessicaMarine1** [comment]
@lesliel789 Due to accessibility concerns, we are changing the language on the gallery page to:  "~~Click on any~~ Select an image to open a slideshow."

**Comment by jfredrickson5** [comment]
Okay, this is ready for review: [preview link](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/gallery-limit/offerings/innovation-lab/)

**Comment by JessicaMarine1** [comment]
@lesliel789 please make sure **all** the items in the checklist are done: [preview link](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/gallery-limit/offerings/innovation-lab/). As soon as you confirm, we'll push all the changes to production :)

**Comment by lesliel789** [comment]
Looks great and all changes from this card are complete. Thank you! Ready for production IMO.
