### ISSUE TITLE
Take down WIL reservation link

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#171]
The WIL reservation link is not allowing users to make reservations for after 2/6. Robin is very unhappy. 

Decision: take it down and add plan B content

Plan B: https://docs.google.com/document/d/1qb-ZITuL_XQ2wtqfUq3xiXefhMjuS-d1K3p2Jz8TGwQ/edit#heading=h.a58rzrcfy3d1

**Comment by JessicaMarine1** [comment]
Per Ryan Booth: vendor is supposed to be making a change that allows users to make reservations after 2/6. Change expected tomorrow.

**Comment by jfredrickson5** [comment]
Implemented in #170
