### ISSUE TITLE
Update WIL page to include RSVP link and video (**to be launched 2/7**)

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite#173]
When the RSVP link is updated:
- [ ] update [content to include RSVP link](https://docs.google.com/document/d/1IhTG7NLkSpGb2KW-gPM-x7qzIlrOsTzY2cFz1oZNL50/edit) [Note: this reverts the changes that were made on 1/26]
- [ ] embed WIL video: https://www.youtube.com/watch?v=-BY-HmsUfoY

**Comment by JessicaMarine1** [comment]
Per the PO, this work should be implemented on Tuesday, Feb. 7

**Comment by jfredrickson5** [comment]
Implemented in #183

**Comment by JessicaMarine1** [comment]
@jfredrickson5 There was a PDF for the reservation instructions implemented before. Chasing down that link.

**Comment by JessicaMarine1** [comment]
@jfredrickson5 Please see https://github.com/GSA/wp2030-microsite/issues/166

**Comment by jfredrickson5** [comment]
@JessicaMarine1 Okay, added the link to the PDF. Seems like the link might be a bit lost under the embedded video, though. Leave it or move it somewhere else?

**Comment by JessicaMarine1** [comment]
@jfredrickson5 I spoke with leslie and she would like to remove the link from under the video and co-locate the link to the instructions closer to the link for the reservation system. She was thinking:

Authorized federal employees and teams may reserve times through our [reservation system](http://reservations.wil.gsa.gov/) to work in the lab for a few hours or all day. Refer to the [reservation instructions](url) for more details.

**Comment by jfredrickson5** [comment]
OK, ready for preview.

**Comment by lesliel789** [comment]
Looks great! The only thing is please change "reservation system
instructions" to "reservation instructions." We're dropping the "system"
there to streamline a bit. Thank you!


Leslie LaMar Rushing
Integrated Solutions PMO (detail)
Public Buildings Service
U.S. General Services Administration
***@***.***
816-359-8581

**Comment by jfredrickson5** [comment]
Updated the wording, does this look ready to go live now?

**Comment by lesliel789** [comment]
@jfredrickson5 Yes thank you! I think the issues in this card are fully addressed and look great. Thanks!
