### ISSUE TITLE
Add new Insight article "Commercial coworking: A solution for USGS" (target production by 2/28 if possible)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#181]
- [ ] On [Insights page](https://workplace.gsa.gov/insights/) add a new entry:

Title: Commercial coworking: A solution for USGS 

Lead photo: https://drive.google.com/file/d/1m1STZBUQ6804Qpl-RdnG7YyHndhEitUG/view?usp=share_link 

Author: Rich Stebbins

Date: whenever it's pushed to prod

- [ ] Create individual page for the article under Insights.

Use approved body copy here:  https://docs.google.com/document/d/19FQ_3SZrq-s1epCH3EsFqWxyApbHD-2v4sLWzidYQEc/edit?usp=sharing 

Use the lead photo on the article page, plus please use these additional photos in the body or at the bottom, depending on how it works with the layout. 
https://drive.google.com/file/d/1e2hVdo9bT_fizmewgTn1RxfZIA1-x0Lq/view?usp=share_link
https://drive.google.com/file/d/1WU0x0tnRqAZnn-1ehL-rUD6NBnqPOdnG/view?usp=share_link 

Please let me know if you have any questions or I need to provide more info. Thanks!

**Comment by weiwang-gsa** [comment]
@JessicaMarine1  Where are those additional photos should go? I can put it at the bottom, but you need both at the bottom?

**Comment by JessicaMarine1** [comment]
@actuallyjenn Do you have any opinions on layout -- especially those two additional pics?

**Comment by JessicaMarine1** [comment]
@lesliel789 Does Rich Stebbins have a title we should include?

**Comment by JessicaMarine1** [comment]
@lesliel789 does all the content in the [google doc](https://docs.google.com/document/d/19FQ_3SZrq-s1epCH3EsFqWxyApbHD-2v4sLWzidYQEc/edit?usp=sharing) go in or just through ###

**Comment by lesliel789** [comment]
Hi,
The article title is "Commercial coworking: A solution for USGS"
His job title is Public Affairs Officer.
For the additional photos, I don't want it to be a problem. For me they can
either be left and right aligned with text wrap like a newspaper or both at
the bottom. Whatever you think is best.
Thanks!

**Comment by lesliel789** [comment]
Sorry - forgot there was anything beyond the article body. The ### symbol
indicates end of content so please do not include that symbol or anything
beyond it. THanks!

**Comment by actuallyjenn** [comment]
In terms of photos, what's in the ticket is different from what's in the google doc. Just want to clarify that what's in the google doc is correct? (If so, Jessica, I'm happy to edit the ticket above!)

**Lead photo:** [Man at counter] https://drive.google.com/file/d/1WU0x0tnRqAZnn-1ehL-rUD6NBnqPOdnG/view?usp=share_link
**Additional photos:** [Vaulted ceilings] https://drive.google.com/file/d/1m1STZBUQ6804Qpl-RdnG7YyHndhEitUG/view?usp=share_link (this is listed as the lead photo in the ticket), [Work tables] https://drive.google.com/file/d/1e2hVdo9bT_fizmewgTn1RxfZIA1-x0Lq/view?usp=share_link

In terms of layout, I think it'd be best if we included the photos in the article directly. This is a common pattern in articles ([Medium example](https://medium.com/designing-atlassian/your-research-reports-are-boring-a4f70296dc5b), [Digital.gov example](https://digital.gov/2023/02/07/collaborate-with-the-tts-public-benefits-studio/)). 

Leslie - can you specify where in the article it might make the most sense to have each of the additional photos? I took a stab at adding it to the google doc, but feel free to move it around!

**Comment by lesliel789** [comment]
Sorry, the photo order in the ticket is correct. I will update the Google
doc.

**Comment by lesliel789** [comment]
I updated the Google doc and rearranged where each photo is requested.
Thanks

**Comment by brentryanjohnson** [comment]
FYI @weiwang-gsa All of these photos 👇  are in the gallery linked in #150 :)

**Lead photo:** https://drive.google.com/file/d/1m1STZBUQ6804Qpl-RdnG7YyHndhEitUG/view?usp=share_link
Alt: A large foyer with a staircase from one level to another and a L-shaped blue couch with coffee table; rugs and carpeting cover part of the area, while exposed concrete floor is exposed elsewhere; a hallway leads to elevators, and another staircase leads down to an area with a green exit sign.

**2 additional photos:**
https://drive.google.com/file/d/1e2hVdo9bT_fizmewgTn1RxfZIA1-x0Lq/view?usp=share_link

Alt: A room with high ceilings with exposed ducts and large windows on one side; two large tables with light fixtures and six chairs around each table, and stair benches wrap around the corner from one wall to the other.

https://drive.google.com/file/d/1WU0x0tnRqAZnn-1ehL-rUD6NBnqPOdnG/view?usp=share_link

Alt: A room with concrete floors and a kitchen area with subway tile; shelves hold mugs and glasses, and there are two taps at one end of a bar; a person in a green T-shirt sits on a bar stool, and there are couches with pillows on them in the foreground along with coffee tables with serving trays with hand sanitizer and potted plants.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson  thank you Ryan! @mark-meyer sortorder for this page should be 3.

**Comment by JessicaMarine1** [comment]
@mark-meyer Per Leslie:
The commercial coworking USGS article needs two changes please. The end quote is missing on Chuck's quote paragraph toward the bottom. Also the very last paragraph of the story is missing. Below the text that is already there please add: “So far we are pleased, but it’s too soon to really tell on its overall use as we're juggling now four different locations for over 90 staff – so we're still figuring things out, but suspect we'll re-compete next year to continue while we have no office or home base,” said Schuster.

**Comment by JessicaMarine1** [comment]
@lesliel789 those last few changes for the USGS article are ready for your review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by lesliel789** [comment]
Looks great thanks! Ready to move to production from my perspective.
