### ISSUE TITLE
Add new Insight article (Building distributed teams - link to 18F blog) desired production 3/14

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#182]
- [ ] Add a new block on the [Insights page](https://workplace.gsa.gov/insights/):
  - [ ] Title: Tips for building distributed teams
  - [ ] Photo:  https://drive.google.com/file/d/12CFVNkVgtfYHFDo6NcdIv2b5rISLPYeM/view?usp=sharing  
  - [ ] Link the article title directly to this page and open in the current window https://18f.gsa.gov/2021/01/12/building-distributed-teams/
  - [ ] Author: GSA 18F
  - [ ] Date: 1/12/21
  - [ ] Use the USWDS 'launch' icon to indicate the link opens an external site; place icon to the right (after) title. 
<img width="57" alt="image" src="https://user-images.githubusercontent.com/6501138/217341664-f82b8d68-1ab4-4988-82a8-37ece1a3d017.png">

 
- [ ] Position on Insights page: Please make this the top left (first) position on the [Insights page](https://workplace.gsa.gov/insights/)
- [ ] Position on homepage: Please make this the left (first) position in the Latest insights section of the [home page](gsa.gov/workplace).
- [ ] Confirm that clicking on the title from the homepage directs the user to the external site.

**Comment by JessicaMarine1** [comment]
@lesliel789 what date do you want us to use for the 18F blog?

**Comment by lesliel789** [comment]
Yikes... is there a best practice for this since our site wasn't around in
2021? I would lean toward using the original pub date 1/12/21 since we
didn't create anything new.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson would you mind provide the image alt description for this photo?  Thank you so much!
 https://drive.google.com/file/d/12CFVNkVgtfYHFDo6NcdIv2b5rISLPYeM/view?usp=sharing

since this is external link, link to external page, do you think we need meta description for this page?

**Comment by brentryanjohnson** [comment]
alt: "A screenshot of a virtual meeting with people holding signs with birthday cakes, birthday messages, and a picture of a person with a beard wearing glasses and a hat; a person in the meeting with a beard and glasses raises their hands in celebration."

**Comment by weiwang-gsa** [comment]
@lesliel789 this issue is ready for QA and can be reviewed here:https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by lesliel789** [comment]
Looks good to me on the homepage and insights page. Thanks!
