### ISSUE TITLE
Add new Insight article "OPM's hybrid toolkit" (by 2/28 target production if possible)

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#184]
On the [Insights page](https://workplace.gsa.gov/insights/), add new entry.

Title: OPM's hybrid toolkit (include the USWDS 'launch' icon to indicate the link opens an external site)

Lead photo: https://drive.google.com/file/d/1IDttNyBt4WoQEMxwJPgcachUGgqeGKVq/view?usp=share_link 

Title links directly to this external site and opens in current window:
https://www.opm.gov/policy-data-oversight/future-of-the-workforce/hybrid-work-environment-toolkit/ 

Date: whenever pushed to production

**Comment by brentryanjohnson** [comment]
@weiwang-gsa 

Lead photo: https://drive.google.com/file/d/1IDttNyBt4WoQEMxwJPgcachUGgqeGKVq/view?usp=share_link

Alt: Sticky notes on paper in a bracket structure; the notes read In-office and Remote while a hand presses a third sticky note that reads Hybrid where the bracket converges, with a stack of yellow sticky notes, markers, and a ruler nearby

**Comment by weiwang-gsa** [comment]
@brentryanjohnson Thank you so much!

**Comment by weiwang-gsa** [comment]
@lesliel789 Ready for review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/insights/

**Comment by lesliel789** [comment]
Reviewed and looks good. Ready to move forward - thanks!!
