### ISSUE TITLE
Add new Insight article "OPM shares future of the workforce guidance" (target production by 2/28 if possible)

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#185]
On the [Insights page](https://workplace.gsa.gov/insights/), add new entry:

Title: OPM shares future of the workforce guidance (include the USWDS 'launch' icon to indicate the link opens an external site)

Lead photo: https://drive.google.com/file/d/15T2q7fhkqFSnB28z__aKd_aH8OGKLStQ/view?usp=sharing 

title links directly to this OPM page and opens in current window:
https://www.opm.gov/policy-data-oversight/future-of-the-workforce/  

Date: whenever it's pushed to production

**Comment by brentryanjohnson** [comment]
@weiwang-gsa 

Lead photo: https://drive.google.com/file/d/15T2q7fhkqFSnB28z__aKd_aH8OGKLStQ/view?usp=sharing

Alt: A diverse group of people in a conference room with two people standing near a whiteboard showing several charts and graphs while four others are seated at a conference table listening; a bicycle is leaning against one wall, and there are several windows on one side of the room.

**Comment by weiwang-gsa** [comment]
@lesliel789 Ready for review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/insights/

**Comment by JessicaMarine1** [comment]
@lesliel789 Can you please confirm these are showing in the order you intended? I thought you wanted reverse chronological order (newest to oldest). With that in mind, I would've thought the 2 OPM articles and the USGS would be on top row and Chuck's blog on the 2nd row left. cc: @weiwang-gsa

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 the order Leslie gave is 192 185 181 184  ( comment in #192), please let me know if anything changes.

**Comment by lesliel789** [comment]
Thanks for double checking. It is in the order I requested. Generally I do
want the newer items at the top, but I wanted these four in this order.
Thanks!
