### ISSUE TITLE
Update WIL page subheader above reservation link

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#186]
- [ ] Please change the subhead from "Test out our space as your workspace" to "Reserve space to work in our lab"

- [ ] Please update the side nav to mirror.

**Comment by lesliel789** [comment]
@weiwang-gsa @JessicaMarine1 @jfredrickson5 Can we please have this ready today 2/7 and push to production with the larger WIL page changes?

**Comment by JessicaMarine1** [comment]
@lesliel789 Can you please review this l[ast change](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/wwang-WIL/offerings/innovation-lab/
)?

**Comment by weiwang-gsa** [comment]
@lesliel789 would you mind reviewing it? you can click linked pull requests->show all checks-->details-->pages/build-->you can preview the changes I made. Thank you!

**Comment by weiwang-gsa** [comment]
Thank you Leslie for verification. Code is merged into main branch. Task completed.
