### ISSUE TITLE
Update WIL page to add Book a tour section (by 2/10 COB)

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#189]
Please update a few things on the [WIL page](gsa.gov/workplace/offerings/innovation-lab/). Changes are all tracked as suggestions in this [WIL content draft doc](https://docs.google.com/document/d/1IlZd337E1fX2v-H3LNTOr4dvQPgwROQVcmlitCXWWhA/edit?usp=sharing). Changes are: 

- [ ] Add one sentence to the Reserve space to work in our lab section. Sentence begins with "For on-site support..."
- [ ] Add a new section / header directly under Reserve space to work in our lab section. The new section header is "Book a tour of our lab" and please add it to side nav. There is one sentence of content in this new section. 
- [ ] Update the Get in touch section per the drafting doc. There will be only one sentence now: "To learn more about the Workplace Innovation Lab, email [WIL1800F@gsa.gov](mailto:WIL1800F@gsa.gov).

**Comment by JessicaMarine1** [comment]
@lesliel789 Please take a look at the changes and let us know if this is ready to go to production: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/JessicaMarine1-patch-1/offerings/innovation-lab/

**Comment by lesliel789** [comment]
Yes looks great and is approved to move to production. Thank you all!


Leslie LaMar Rushing
Integrated Solutions PMO (detail)
Public Buildings Service
U.S. General Services Administration
***@***.***
816-359-8581

**Comment by JessicaMarine1** [comment]
@jfredrickson5 ready to go to prod!
