### ISSUE TITLE
update Commercial Coworking page text & add photo gallery

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#190]
On the [Commercial coworking](https://workplace.gsa.gov/offerings/commercial-coworking/) page:
  

- [ ] Under `The contract is not section`, change the first bullet from this:

"A long-term solution for agencies with space requirements beyond 12 months. To secure additional months of coworking space, we must recompete the task order, and an agency may be assigned to a new space managed by a different vendor."

To this: 
"A long-term solution for agencies. To accommodate groups requiring space for more than 12 months, we will recompete the task order, and agencies may be assigned to a new space managed by a different vendor."

- [ ] Also, please end the [Commercial Coworking space section](https://workplace.gsa.gov/offerings/commercial-coworking/#section_1) after the "Contact our team..." sentence. 

- [ ] Create a new "View photo gallery" section right where the photos currently live (and reflect in the side nav).

- [ ] Remove the addresses that accompany the three existing photos. 
- [ ] Keep the existing 3 photos and have text under them "View the full gallery." that links to a new photo gallery page you will make please.  

   Note: Model off the [WIL page](https://workplace.gsa.gov/offerings/innovation-lab/) and the [WIL gallery page](https://workplace.gsa.gov/offerings/innovation-lab/gallery/) please. 

- [ ] Here are the photos to put in the commercial coworking photo gallery:

https://drive.google.com/drive/folders/1O3YEQdhXYhzN8VHMgr1NftPfa7y6esSN?usp=sharing

I think there are about 50 photos. Please let me know if I need to reduce the number.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson might need your help here for the alt text for all those pics :)

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 I'm getting a start on the `alt` text in [this 🔒 doc](https://docs.google.com/document/d/1r0jaVj-3bWl_hbUQzjCYBqHpXf-9AStAfwjQ_4elm5A/edit?usp=sharing).

**Comment by weiwang-gsa** [comment]
@brentryanjohnson   I also added below photos that also need alt description to your document at the bottom. Thank you so much for your help, really appreciate it!

Issue #184:

Lead photo: https://drive.google.com/file/d/1IDttNyBt4WoQEMxwJPgcachUGgqeGKVq/view?usp=share_link

Alt:

Issue #185:
Lead photo: https://drive.google.com/file/d/15T2q7fhkqFSnB28z__aKd_aH8OGKLStQ/view?usp=sharing
Alt: 

Issue #181:

Lead photo: https://drive.google.com/file/d/15T2q7fhkqFSnB28z__aKd_aH8OGKLStQ/view?usp=sharing
Alt: 

2 additional photos:
https://drive.google.com/file/d/1e2hVdo9bT_fizmewgTn1RxfZIA1-x0Lq/view?usp=share_link
Alt:

https://drive.google.com/file/d/1WU0x0tnRqAZnn-1ehL-rUD6NBnqPOdnG/view?usp=share_link

Alt:

**Comment by mark-meyer** [comment]
There were 5 images that were lower-resolution than the size we are showing in the gallery. To make these work we would need to enlarge them, which will reduce their quality.

**These images are:**

- CA.png
- conference collaboration.jpeg
- Conference Room 2.png
- Coworking.jpeg
- unnamed copy.jpeg

If you have original files or files with a bit more resolution, we can include them. I would recommend against using these five as-is, though.

**Comment by JessicaMarine1** [comment]
@lesliel789 please see Mark's comment about the 5 pictures that have low-resolution. What would you like to do?

**Comment by lesliel789** [comment]
I don't have access to better images so let's leave those 5 out please.
Thanks for flagging!

**Comment by mark-meyer** [comment]
Staging build here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@mark-meyer Can you take another look at the pics on the [commerical co-working page](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/commercial-coworking/)? They look pixelated to me:



![Image](https://user-images.githubusercontent.com/92383362/221601719-9c6345fb-c60d-4cff-9297-bb3d4fbadc6e.png)

**Comment by mark-meyer** [comment]
@JessicaMarine1 these images have not changed. Also, they look good on my screen — they are actually much higher-resolution than they need to be for these thumbnails. Maybe we can get a 3rd opinion from @weiwang-gsa or @jfredrickson5?

**Comment by weiwang-gsa** [comment]
@mark-meyer @JessicaMarine1  it looks good on my side, I am using laptop though, not sure if Jessica using bigger screen monitor? As my home dell monitor doesn't work with my new laptop, I can't verify the resolution for the bigger screen.

**Comment by JessicaMarine1** [comment]
@lesliel789 can you please review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

Also, this concludes all the work for the next batch. Do you want to stick to the Thursday deployment, or move it up? If we move it up, we will change the date on insight articles, as needed.

**Comment by lesliel789** [comment]
Commercial coworking gallery looks awesome! Thanks for all the work on this. It's ready for production from my perspective. You rock!
