### ISSUE TITLE
Add new Insight article "The future of work starts now" (target production by 2/28 if possible)

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#192]
On the [Insights page](https://workplace.gsa.gov/insights/), add new entry.

Title: The future of work starts now (include the USWDS 'launch' icon to indicate the link opens an external site)
Author: Chuck Hardy
Lead photo: https://drive.google.com/file/d/1Ch3V4COGoCi6ZAVVAVQRhLZbMvMg3tTs/view?usp=sharing 

Title will link directly to the gsa.gov blog page located here and opens in current window: 
https://www.gsa.gov/blog/2023/02/13/the-future-of-work-starts-now 

Date: February 13, 2023 (If you can manually override the date to NOT be the day we push to production, please do so to align with when Chuck's blog actually published on gsa blog.)

**Comment by weiwang-gsa** [comment]
@lesliel789 
1. Yes, date can be any date you specified.  So it can be replaced by Feb 13th, 2023
2. Is the launch icon the below screenshot? Do you want to include USWDS launch icon positioned at the beginning of the title"The future of work starts today" or at the end of the title? 


![Image](https://user-images.githubusercontent.com/119954777/220450263-c9cc87da-fea6-498d-a0c5-342d1e32124e.png)

**Comment by lesliel789** [comment]
1. Great thank you!
2. Yes that's the icon Jenn had recommended when we talked about this a few
days ago. Looks great! And let's please put it at the end of the title.
Thank you for having me specify!

Thanks much!
Leslie

**Comment by weiwang-gsa** [comment]
@lesliel789  this issue is ready for review here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/wwang-patch3/insights/

**Comment by JessicaMarine1** [comment]
@lesliel789 there is a discrepancy between the title you asked us to use and the title on the actual article. Do you want them to match?

**Comment by lesliel789** [comment]
I'm not seeing it but please use whatever the title is on the live GSA blog
piece. This looks good.
I would like the new pieces as they come online to be at the top of the
insights page / list please? New pieces inserted at the top.
Is that doable please?

**Comment by weiwang-gsa** [comment]
@lesliel789  I updated live site title to match with actual external link title, which is "The future of work starts now", the user story says "The future of work starts today", since you are ok with current setting, I am assuming I don't need to change "now" back to "today", we are good for this one.  As for order, yes, we can change the order to your like, but you have several new pages for insights (#192, #184, #185 and #181), can you give us the order list of all these pages?

**Comment by lesliel789** [comment]
Thanks! Yes, we will leave as "now."
And this order please:
192
185
181
184
Thanks so much!
L

**Comment by lesliel789** [comment]
Sorry I don't understand your first question. I'd like the newest insights
at the top of the Insights page, but I'm not sure what the question means.

Re order: Do you mean the home page pulls the *first* three Insights ever
created or it pulls the *last* three created?

If it's the last, then can you "create" the articles in reverse order so
that they autopopulate the home page in the order I requested?

Note that may or may not be relevant: I'd rather have this order of
articles on the home page and Insights page than have Chuck's blog date
match the actual blog post date. So if the date field is a driver, then we
can revert to having Chuck's blog be dated the same as the other three
whenever pushed to production.

Regardless of if the home page can show the most recent insights or not, I
do want the Insights page to have the newest at the top please.

I hope this info helps. Thanks for working this and please let me know if
it's better to hop on a meet to discuss.
Thanks, L

**Comment by lesliel789** [comment]
Ah thank you! Sorry I wasn't quite there before.
Decisions:
I will add a new ticket to pursue the coding change so the homepage pulls
the newest three.
And we'll do option 2 above -- this will be a future action and we will not
delay the current batch.
Thanks!

**Comment by lesliel789** [comment]
Reviewed and looks good. Ready to move forward - thanks!!
