### ISSUE TITLE
update WIFM page asap (current download function is not following business rules to only allow gov emails)

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#193]
The [WIFM page](https://workplace.gsa.gov/offerings/modeling-tool/) of the website. 
Change the section header and side nav from "Download WIFM" to "Request WIFM"
Change the sentence under that section to read: "The WIFM tool (Excel file) is available at no charge to federal employees with official government email addresses. Email workplace@gsa.gov to request the tool. Please allow up to three business days to receive the file.

The WIFM needs to NOT link to the form it has been linking to please. 

The urgency is that the page's current functionality is allowing non-gov people access to the tool. Plus as soon as today (2/16) and NLT 2/22, Robin, Katy and Nina are all sending emails to peers advertising this website. Traffic is expected to spike. Sorry for the requested quick turn. Thank you! @JessicaMarine1

**Comment by JessicaMarine1** [comment]
@lesliel789 Please review the proposed changes at: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/JessicaMarine1-patch-2/offerings/modeling-tool/

**Comment by JessicaMarine1** [comment]
@weiwang-gsa or @jfredrickson5 Leslie has reviewed these changes and approved them going to production. Please merge to main on Friday (2/17) when you have a chance. Thank you!

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 code is merged to Main branch today (02/17/2023) at 7:11am ET. I verified on production site. Please double check just in case.

**Comment by JessicaMarine1** [comment]
Moved to shipped; Added release note 2/17
