### ISSUE TITLE
Update "office is necessary" principle on homepage

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#201]
on the site homepage, please change the text for the second guiding principle from:
Offices will remain critical to collaborate, maintain connections, and access secure resources. They will also continue serving as primary workspaces for those who can’t (or don’t want to) work from home.

to
Offices will remain critical to collaborate, maintain connections, access secure resources, and serve as primary workspaces for those who can’t (or don’t want to) work from home.

Will this shorten it enough that the vertical spacing between icons becomes consistent? That's my objective.

**Comment by mark-meyer** [comment]
@JessicaMarine1 and @lesliel789 I did a quick in-browser check. At least on my computer (may be different if others have different font/magnification settings), the change is not enough to make that block only take up two lines:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/7340303/221944641-0a691cbc-d219-4924-a39e-7d81e058d366.png">

 Another option (in addition to shorter text) is to bump the width of that column on notch :  
 
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/7340303/221945000-8f9509fa-15bb-42c8-9373-9c78aef31feb.png">

**Comment by lesliel789** [comment]
Thanks for showing this @Mark Meyer - AD ***@***.***> . It looks
like approx. 20 words is the max to keep it on two lines. Does the below
get us there?

Offices will remain critical to collaborate, connect, access secure
resources, and host those who can't or don't want to work from home.

**Comment by mark-meyer** [comment]
It's up on the staging branch for @lesliel789: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/
