### ISSUE TITLE
update offerings page text (federal coworking teaser)

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#211]
On the [offerings page](gsa.gov/workplace/offerings), update the federal coworking text to:

Federal agencies share space and services in GSA owned and leased locations. Employees from several agencies will work in an open office, sharing furniture, meeting rooms, IT infrastructure, and support spaces.

**Comment by JessicaMarine1** [comment]
@mark-meyer is there a way to re-center the text vertically across the picture? https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/JessicaMarine1-patch-4/offerings/

**Comment by mark-meyer** [comment]
@JessicaMarine1 I think there is — The text on top is getting some extra top-margin space from the styling on the top paragraph. We would need to remove that (and make sure we don't break things on mobile).

**Comment by actuallyjenn** [comment]
@mark-meyer per jessica's comment to center the text on the images:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/6501138/222764704-88edca45-520b-4aba-bf00-0e44dd8a4f21.png">

**Comment by lesliel789** [comment]
I feel like the vertical centering isn't quite right on the federal
coworking one, but since the descriptions vary in length, I think having
the headings top aligned with the images may look better. @Jessica Marine -
AD ***@***.***> what was the driver or what are your thoughts
on this please?

Also please remove the word "will" in the federal coworking description
here:
Employees from several agencies will work in an open office

Pretty sure this was my bad in submitting the content change - sorry.
Thanks, Leslie

**Comment by mark-meyer** [comment]
Hi @lesliel789 I tried aligning the text to the top per your suggestion and I think it looks good (I also removed "will"). 

It's up on the [staging branch](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/).

**Comment by lesliel789** [comment]
All looks good thanks! Moving to done.
