### ISSUE TITLE
Curly v. straight apostrophes

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#217]
We are not consistent in how we are using apostrophes across the site:

![Image](https://user-images.githubusercontent.com/92383362/222789892-312d9c44-c6bc-462e-b511-add7ac371f7e.png)

Need to:

- [x] Determine whether curly v. straight is our default -- should be curly
- [x] Change the following straight apostrophes to curly:
  - [x] Homepage (opening paragraph): We know there `isn't` a one-size-fits-all approach for agencies, so we have multiple tools and services to meet you where you are and to customize for your needs.
  - [x] Insights page (title): `OPM's` hybrid toolkit 
  - [x] Contact page (first bullet): If `you're` interested in any of our offerings, please reach out to your [national customer lead](https://www.gsa.gov/about-us/organization/public-buildings-service/office-of-portfolio-mgmt-customer-engagement/office-of-customer-engagement/account-management-program/pbs-national-customer-leads) or your [regional account manager](https://www.gsa.gov/about-us/organization/public-buildings-service/office-of-portfolio-mgmt-customer-engagement/office-of-customer-engagement/regional-client-solutions).
  - [x] NRC article (2nd paragraph): PBS and NRC partnered on a [workplace engagement](https://workplace.gsa.gov/offerings/workplace-engagements/) study that analyzed the `NRC's` space needs and recommended ways to operate more efficiently.

**Comment by JessicaMarine1** [comment]
@actuallyjenn Is there USWDS guidance on this?

**Comment by actuallyjenn** [comment]
@JessicaMarine1 i don't think there is uswds guidance on this but we should be using the default style that the font itself shows - this is usually best practice. in this case, it would be the "curly" style, which uswds uses in their own content. i'm guessing the straight came from a copy/paste.

**Comment by brentryanjohnson** [comment]
[Keyboard shortcuts for curly quotes](https://practicaltypography.com/straight-and-curly-quotes.html)

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 for markdown pages, we used the markdown-it config auto fix it, for other pages (html, .njk or quote coming from variable values), have to manual update it. This issue is ready for QA: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
The places I identified look corrected to me. Moving to some.
