### ISSUE TITLE
Update external links to reflect new design pattern (part 2)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#219]
<img width="57" alt="image" src="https://user-images.githubusercontent.com/6501138/217341664-f82b8d68-1ab4-4988-82a8-37ece1a3d017.png">.
New design pattern is needed throughout the workplace site for external links:
- [ ] Use the USWDS 'launch' icon to indicate the link opens an external site
- [ ] External pages should open in the current window
- [ ] Apply new design pattern to:

1 place on the [WIL offering page](https://workplace.gsa.gov/offerings/innovation-lab/)

![Image](https://user-images.githubusercontent.com/92383362/224310466-9ab7e0e2-bf9b-4165-aa6e-d205cd9aeda3.png)
----------
2 places on the [Workplace engagement offering page](https://workplace.gsa.gov/offerings/workplace-engagements/)

![Image](https://user-images.githubusercontent.com/92383362/224311005-b6475a9f-0a65-42ea-8662-51ed5621674f.png)
------------
10 places on the [commercial coworking offering page](https://workplace.gsa.gov/offerings/commercial-coworking/)

![Image](https://user-images.githubusercontent.com/92383362/224312009-1cb9135f-bf6e-4add-9207-9e6ed7056dea.png)
--------------
3 places on the [WIFM offering page](https://workplace.gsa.gov/offerings/modeling-tool/)

![Image](https://user-images.githubusercontent.com/92383362/224312415-c9e6baaf-4c5d-470f-bc9f-96f39ccbfa38.png)
----------------
2 places in the [USGS insight](https://workplace.gsa.gov/insights/commercial-coworking-a-solution-for-usgs/)

![Image](https://user-images.githubusercontent.com/92383362/224313054-d390c52b-3f79-4b53-a1c6-2e8182b85f96.png)
----------------
2 places in the [USAID insight](https://workplace.gsa.gov/insights/usaid-gsa-consolidating-space-to-drive-cost-avoidance/)

![Image](https://user-images.githubusercontent.com/92383362/224313553-6a85fb88-a77c-41a1-9ba3-a0c85b9ba96a.png)
![Image](https://user-images.githubusercontent.com/92383362/224313582-474aae37-acca-4038-82a9-5443116f99e0.png)
-----------------
2 places in the [NRC insight](https://workplace.gsa.gov/insights/nrc-gsa-space-reduction-and-cost-savings-in-new-lease/)

![Image](https://user-images.githubusercontent.com/92383362/224314228-11de6af5-a685-4389-aaea-56ff14abf33d.png)

**Comment by JessicaMarine1** [comment]
This issue applies the new design pattern to individual offering and individual insight pages. Changes to the main pages of the site are covered by #71

**Comment by JessicaMarine1** [comment]
@JessicaMarine1 needs to add list of items to update in the individual offering and individual insight pages

**Comment by JessicaMarine1** [comment]
@actuallyjenn Can you please take a look at the places that I've identified as needing the external link design pattern in the individual offering / insight pages and confirm these look right to you? ty

**Comment by actuallyjenn** [comment]
yep, these look like all of the places. thanks for gathering this jessica!

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 this is ready for QA here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
Looks good. Moving to done!
