### ISSUE TITLE
Insights on homepage (links to external sites) -- needs to be implemented ASAP

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#222]
When implementing #205 to change the insights that display on the homepage, the link to the external sites for the first two articles (Chuck's blog & OPM FOW guidance) was lost. 

- [ ] The two insights on the homepage -- Chuck's blog & OPM FOW guidance -- need to link out to their respective external sites.
- [ ] Apply new design pattern for external sites by the title for each. 
<img width="57" alt="image" src="https://user-images.githubusercontent.com/6501138/217341664-f82b8d68-1ab4-4988-82a8-37ece1a3d017.png">.

**Comment by JessicaMarine1** [comment]
@lesliel789 the first two insights displaying on the homepage are _not_ linking to the external sites correctly. We're fixing this ASAP and will push the change to `production` as soon as it's ready.

**Comment by lesliel789** [comment]
Weird - but ok thanks much!

**Comment by weiwang-gsa** [comment]
@lesliel789 Issue is been fixed, it is Ready for QA here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/hotfix-issue222/

**Comment by lesliel789** [comment]
The links work for me in the test environment. Thanks! Moving the ticket to done.

**Comment by weiwang-gsa** [comment]
@lesliel789 Thank you so much! Just let you know that this is released to production site and can be reviewed at : https://workplace.gsa.gov/ 

Once you are done with final verification on production site, please kindly move it to "Shipped". Thank you so much, we really appreciate it!

**Comment by lesliel789** [comment]
@weiwang-gsa it looks good live and I'm moving this to shipped. I really appreciate YOU providing a quick fix! Thanks!
