### ISSUE TITLE
Elevate prominence of WIL reservation link - Target production no later than 4/6

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#227]
- [ ] On the [homepage](https://workplace.gsa.gov/), add a new section to elevate the prominence of the WIL booking link
   Design: https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=1711-979&scaling=scale-down-width&hotspot-hints=0&hide-ui=1

- [ ] On the [offerings page](https://workplace.gsa.gov/offerings/), add a new link under the WIL offering
   Design: https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=1779-384&scaling=min-zoom&page-id=1711%3A851

Link for each should be to: http://reservations.wil.gsa.gov/ that opens in same tab

**Comment by lesliel789** [comment]
@JessicaMarine1 we discussed this via chat in late Feb but I realized today I didn't put a ticket in til today - sorry.

**Comment by JessicaMarine1** [comment]
@actuallyjenn this one will require some of your design magic!

**Comment by lesliel789** [comment]
Let's please user test our options with a few people. Let me know if you need me to identify candidates. I'll want to briefly describe the findings in the user feedback section of [this deck](https://docs.google.com/presentation/d/1ltxyQpqEcl1VoujRTkfJvyYhCobKQaXKXPKVkYiLAxc/edit?usp=sharing). Then we can let PBS leadership know why we're taking the approach and get their feedback as well.

**Comment by actuallyjenn** [comment]
@lesliel789 we'll work on usability testing the options but i mocked up four variations: https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=1711%3A858&scaling=min-zoom&page-id=1711%3A851&hide-ui=1

**Comment by JessicaMarine1** [comment]
Usability findings: https://docs.google.com/presentation/d/1FhUDgYm8UsXqV5HhowlE-b8hzrjE4u4gF_pSXdTlQXo/edit#slide=id.g2233f344949_0_143

Provided to PO 3/27 -- Need decision(s) from PO on how to proceed.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 @actuallyjenn Please confirm if I can copy paste below text directly from design mock, maybe Washington, D.C. instead?


![Image](https://user-images.githubusercontent.com/119954777/229557635-5aa5eb40-feca-40b2-9893-cf049a2e5524.png)

**Comment by weiwang-gsa** [comment]
@actuallyjenn This is ready for UI review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
Moving this back to `In Progress`. Still waiting on text for homepage.

**Comment by SamCioffi** [comment]
I took this from the google doc version of the MVP: 
"Explore design, technology, and furniture options and reserve space to work in GSA’s headquarters in Washington, DC" 

Please use this as the text under, "Visit the Workplace Innovation Lab". 
Thank you!

**Comment by weiwang-gsa** [comment]
@SamCioffi  This issue is ready for QA: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by SamCioffi** [comment]
@weiwang-gsa approved, thank you!
