### ISSUE TITLE
Add new offering (AEI IDIQ) - Target production date 3/27

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#232]
We would like to add a new offering to the website -- AEI IDIQ.

On the [offering landing page](https://workplace.gsa.gov/offerings/) - see design in comment below:

- [ ] Title: Leverage our collaborative design services
- [ ] Description: Get access to top industry workplace and design experts with competitive pricing through our indefinite delivery, indefinite quantity contract
- [ ] Link: Read more about our AEI IDIQ → 

- [ ] On the new offering page, use [this content](https://docs.google.com/document/d/11hpmWCF0BnYF0zayaNgus5R_nUOaAv1XNo9fVl-EPDE/edit#bookmark=id.rldv166iqaq5) please.
- [ ] for the numbered list, consider USWDS component: [https://designsystem.digital.gov/components/process-list/](https://www.google.com/url?q=https://designsystem.digital.gov/components/process-list/&sa=D&source=docs&ust=1679344778860831&usg=AOvVaw29_GLDlWRhmNMwDSWLi7Mo)

**Comment by lesliel789** [comment]
The order above in @actuallyjenn 's mock up screen grab is approved. Content is finalized and approved. I linked it in the description above. Moving this to Ready To Work. Thanks!

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 this ticket is ready for review : https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/

**Comment by actuallyjenn** [comment]
@weiwang-gsa this looks good however... the logo in the header looks weird to me on my computer - do you have that issue too? 

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/6501138/227037803-675378ef-390d-4bd1-b5b6-7987e264c201.png">

**Comment by actuallyjenn** [comment]
wei, i also noticed a missing period at the end of the **Get in touch** section. i went in to make the change in staging so let me know if i did that wrong. 

@lesliel789 - just noticed the URL. right now it'll be `https://workplace.gsa.gov/offerings/leverage-design-services/`but i wonder if it should be `/offerings/design-services/`or `/offerings/aei-idiq/ `instead? (none of the other links are stylized as verb first)

**Comment by weiwang-gsa** [comment]
@actuallyjenn thanks for catching it, I did not touch styles for header section though, I will check up with Jeff regarding this. and I will wait for leslie's response to update the URL once it is finalized.

**Comment by weiwang-gsa** [comment]
@actuallyjenn just let you know that header issue is fixed. The only remaining part is the if the URL need to be updated.

**Comment by lesliel789** [comment]
Thanks for bringing this up, team! I'd prefer offerings/aei-idiq please. In
the future, we may add a different idiq offering page, and design services
can be obtained a few different ways.
Thanks!

**Comment by lesliel789** [comment]
This looks great! The only outstanding item now is a potential content tweak in the second paragraph. @JessicaMarine1 I'm ok with either option you proposed in the Google doc. Once Alison replies, will you please add the tweak to this card?

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 update is completed. please review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@weiwang-gsa please remove the "s" off the end of Regulations in that second paragraph. otherwise, this is good to go to production.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa this is good to go to production.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 @lesliel789 this issue is deployed to production on 03/23/2023 at 11:43 AM ET. It is ready for final production verification: https://workplace.gsa.gov/

Once it passes the final verification, please move it to "shipped", thank you~
