### ISSUE TITLE
Add new insight (Nina's FOW and the path forward) - Target production no later than 4/6

### ISSUE THREAD

**Issue by lesliel789** [GSA/wp2030-microsite#236]
- [ ] Add a new block to [Insights page](gsa.gov/workplace/insights) in the top left (position 1) spot 
- [ ] Add a new block to the insights section of the [homepage](gsa.gov/workplace) in the left position
- [ ] Title: The future of work and the path forward
- [ ] Author: Nina Albert
- [ ] Date: whenever it goes to production
- [ ] Lead photo: https://drive.google.com/file/d/1ZPKZILIj2Kb4yhxSDfq5BkXGSCo8JvqS/view?usp=sharing 
- [ ] Create a new insights child page. 
- [ ] Content is located [here](https://docs.google.com/document/d/1LfpuatGpB6ZzFa0ZD7P-zxGVKJ2r5gdfSG-FzrDZn_U/edit#bookmark=id.lgyiter8o7ge).

**Comment by JessicaMarine1** [comment]
Changing target production date from 3/27 to TBD -- the necessary approvals weren't obtained in time to launch by 3/27

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 we need the signature image.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa decision was made to remove Nina's signature from the insight. I've updated the content linked above.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson Would you mind provide the image alt for https://drive.google.com/file/d/1ZPKZILIj2Kb4yhxSDfq5BkXGSCo8JvqS/view?usp=sharing? Thank you so much!

**Comment by weiwang-gsa** [comment]
@actuallyjenn this is ready for UI review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by actuallyjenn** [comment]
this looks good!

**Comment by weiwang-gsa** [comment]
@SamCioffi this ticket is ready for your review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by SamCioffi** [comment]
Hello! My only concern is the zoom/ crop of Nina's headshot. Does the ratio or size of the headline image need to be this way, or can it be the original proportions?

**Comment by SamCioffi** [comment]
@weiwang-gsa Please include the white space above Nina's head and the space below her shoulders. If the verticality of the image is a problem, we could use a grayspace rectangle behind like we've done in the past behind this image, but I defer to the design experts here! 

![Image](https://user-images.githubusercontent.com/128738447/230117633-6255270d-f19a-4c47-b7d3-16c7170fcfeb.png)

**Comment by weiwang-gsa** [comment]
@SamCioffi Yes, I can add gray space as shown. Do we do the similar thing for the other ticket ( issue#245)? Add top and bottom grey space and make the image crop in the middle?

**Comment by weiwang-gsa** [comment]
@SamCioffi Update is made, it is ready for QA: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by SamCioffi** [comment]
@weiwang-gsa I think our threads got conflated. Will approve the other thread for the video link. Please LMK if you are able to adjust the cropping on the article page to include all of Nina's head/ hair and zoom out further. Thank you!

**Comment by weiwang-gsa** [comment]
@SamCioffi, Nina's head/hair seems ok on my screen below. 


![Image](https://user-images.githubusercontent.com/119954777/230207973-1c396492-1ec7-42e7-9718-744b24ff027f.png)

**Comment by JessicaMarine1** [comment]
@SamCioffi this seems to look different on different screen sizes. When I have it opened on my large external screen, it looks like this:
![Image](https://user-images.githubusercontent.com/92383362/230231221-4d58f26c-919a-4c69-bf62-8ec3e12b7275.png)

However, when I reduce the screen size or pull it to my laptop, it looks like this:
![Image](https://user-images.githubusercontent.com/92383362/230231378-82da6650-5494-4deb-af2f-18a317d5ad6b.png)

And it looks fine on mobile.

**Comment by JessicaMarine1** [comment]
@SamCioffi the bottom line is -- this is a known (and difficult to solve for) issue with photos and responsive design. Because the image box is set to the page width, it will weirdly crop vertical photos. Three options here:
1. Leave as is with the understanding that it will crop Nina's pic some if the user's screen is set _really_ wide.
2. Choose a new banner photo (one with a horizontal alignment). 
3. Move Nina's picture to the body of the article _and_ pick a new banner photo. 
I'd be happy to hop on a call with you tomorrow to discuss, if needed.

**Comment by SamCioffi** [comment]
@JessicaMarine1 Thank you for cracking this for me! Yes, I'm looking at it on my very wide 27" monitor. I will find out if OSC has any banners we can use at the top and Nina's photo in the body, will get back to this team ASAP.

**Comment by weiwang-gsa** [comment]
@SamCioffi originally the image width the same as header width, so it will dynamically change the image ratio to go with header width as responsive design, it will cropped the image as you zoom or use wider screen. I removed this width go with header style and make it keep the image ratio and increase the image height. please let me know if you approve the change, you can view it in my test branch:https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/wwang-patch-7/pages/insights/future-work-path-forward/

**Comment by SamCioffi** [comment]
@weiwang-gsa This looks great, thank you for you patience in getting this right for the monitor ratio sizes. Moving to approved
