### ISSUE TITLE
New Insight: Build a future-ready workforce - Target production no later than 4/6

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#245]
Please add a new insight that links out to external page:

- Title: Videos: Build a future-ready workforce (external link icon)
   - Note: Article title links directly to this external page and opens in the same tab for the user.
- Link: https://www.gsa.gov/about-us/events-and-training/gsa-training-programs/fast-overview/build-a-futureready-workforce-resource-page 
- Lead photo for insight page: [marketing image](https://www.gsa.gov/cdnstatic/General/FAST2023_Future%20Ready%20Workforce%20Event_Banner-noREG2.png) 
- Date: production date
- Position on insight section of the [homepage](https://workplace.gsa.gov/): middle position
- Position on [insight landing page](https://workplace.gsa.gov/insights/): middle position top line

**Comment by SamCioffi** [comment]
Let's use the left half and crop out the portion with the person, even if
it's just the graphic on white background. I don't have the right tools to
crop it myself like Photoshop, but let me know if you need me to send it
back to someone else for revision or formatting!


Samantha Cioffi
Workplace Strategist
_________________

U.S. General Services Administration
Phone: (212) 264-8212
Cell: (551) 370-4389

**Comment by weiwang-gsa** [comment]
@SamCioffi  is below what what  you want?  The bottom part is white, I have to set new canvas and fille background with white to get it cropped with person.

![Image](https://user-images.githubusercontent.com/119954777/229219847-f9cce002-d7ce-456f-9ef0-de212bf2151a.png)

Below is 4:3 ratio can get ( Red), you can see even text get cut off. If possible, I highly suggest to choose a different lead photo. 


![Image](https://user-images.githubusercontent.com/119954777/229220504-34174b12-42ac-4349-93a8-5ec8fe16adac.png)

**Comment by SamCioffi** [comment]
Hello! The crop with person is great. Can the image be centered, so white is on top and bottom?

**Comment by weiwang-gsa** [comment]
@SamCioffi Thanks, since we adding fill color, I just keep the whole image and cropped on the filled in gray space, it looks like below, currently code change is under peer review. Once it passed the PR review, I will update status and provide you with Staging build URL for you to review. 

![Image](https://user-images.githubusercontent.com/119954777/230192494-11d2d553-5877-46c8-ac38-a661d26364c0.png)

**Comment by weiwang-gsa** [comment]
@SamCioffi this issue is ready for QA: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by SamCioffi** [comment]
@weiwang-gsa Is it possible to still crop less on the image of Nina on the article page? I'd prefer if her hair were not cropped out. I also feel as though it is too close to her face. Please let me know if we need to go back to OSC for another image, but I'd assume all of our portraits are in vertical format! 

The video link and thumbnail looks great. TY!



![Image](https://user-images.githubusercontent.com/128738447/230196952-3825060b-601e-4fa8-bd77-23e840d19bb6.png)

**Comment by SamCioffi** [comment]
Moving this thread to approved as the video thumbnail and link portion are considered approved; the card associated with the Nina article link is still active. thank you!

**Comment by weiwang-gsa** [comment]
@SamCioffi strange, it doesn't crop on my side, this what I saw, probably you need to clear browser cache and refresh the link? 

![Image](https://user-images.githubusercontent.com/119954777/230203608-2b40df66-2df6-4853-9421-32443965d63d.png)
