### ISSUE TITLE
USWDS bug | In-page navigation menu

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#250]
Current Offerings in page nav, if you manually click the in page nav section title from top to bottom, the position indicator is off. If you click nav section title from bottom up order, the position indicator is positioned correctly. It happened both on production site (USWDS 3.3.0)  and with USWDS 3.4.1.  See screen shot below:

![Image](https://user-images.githubusercontent.com/119954777/229546921-c1a194f8-7e79-4ec4-8b77-c2974f886dd5.png)

**Comment by JessicaMarine1** [comment]
@actuallyjenn @weiwang-gsa would you mind adding the details above?

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 I added the issue details, this may not be USWDS bug, somehow it conflicts with our current offering page settings, had not figured out what is the root cause yet. I tested this morning to add in-page nav for insights page, which turns out working properly for insights page, somehow somewhere it conflicts with offerings pages, will check up with Jeff today at tech sync if he has some clue.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa I think the behavior in the picture above is correct because "View photo gallery" is visible on the page as well.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 the position indicator should anchor the header comes to top section. so when manually click the "Reserve space to work in our lab" it set the focus on that header, and made it the header for the top section of the screen, the position indicator also should stays on that header text for in-page Nav.  This is fixed here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/wwang-patch-7/offerings/innovation-lab/, will create PR

**Comment by JessicaMarine1** [comment]
Your fix looks good! Moving to done.

**Comment by JessicaMarine1** [comment]
@SamCioffi just letting you know that we fixed the in-page navigation scrolling issue: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/wwang-patch-7/offerings/innovation-lab/
