### ISSUE TITLE
Remove sentence from commercial coworking page

### ISSUE THREAD

**Issue by anjunainaustin** [GSA/wp2030-microsite#260]
We would like to remove a sentence from the content on the commercial coworking page.

On the [commercial coworking page](https://workplace.gsa.gov/offerings/commercial-coworking/) right above View Photo Gallery - we would like to remove “Contact our team to discuss commercial coworking locations in your area and how you can set up an on-site visit.”

-----------------
**Final review:**
Confirm intended functionality is working on:
- [ ] Desktop
- [ ] Mobile

**Comment by JessicaMarine1** [comment]
@anjunainaustin The requested text change to the commercial offering is in progress. We’ve made the change, so now it’s time to engage you in the process. 

You should see that the card is now in the QA column of the board. This is an opportunity for you to review the change on the STAGING environment (https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/commercial-coworking/) — you might want to bookmark that URL — before pushing it to production. If the change looks good to you on STAGING, you’ll move this card to the DONE column and comment below “This looks good. Moving to done. Ready to push to production” (or something similar). Once we push to PRODUCTION, we’ll let you know and ask you to do one last review on gsa.gov/workplace before you move the card to “Closed (Shipped)”

Please let me know if you have any questions.

**Comment by anjunainaustin** [comment]
This looks good. Moving to done. Ready to push to production
