### ISSUE TITLE
New Fast Track page (deploy by 7/17)

### ISSUE THREAD

**Issue by anjunainaustin** [GSA/wp2030-microsite#264]
We would like to add a new offering to the website for Fast Track.

- [ ] URL for new offering page: https://gsa.gov/workplace/offerings/fast-track/
- [ ] Content: https://docs.google.com/document/d/16sKw2cjwBego9oEHMg-w6WwSga1-WmpsM-NtZ6eaXo0/edit

Design for new Fast Track Page: https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?type=design&node-id=2224-748&t=8HQjuIi8yWRVA2jM-0&scaling=scale-down-width&page-id=2224%3A580&starting-point-node-id=2224%3A583&hide-ui=1

Floor plans are available here (slides 17-21): https://docs.google.com/presentation/d/1ipOa4Hm1_-DSC89sHVU2flCKLfsULZejJjLLNfmkYjY/edit#slide=id.p7 [if we need in a different format, please let the PO know]

-----------------
**Final review:**
Confirm intended functionality is working on:
- [ ] Desktop
- [ ] Mobile

**Comment by anjunainaustin** [comment]
@JessicaMarine1 We will be seeking clarity from OSC on approval process before we need an initial mock-up of this, but if you could provide the hard deadline by which the approved content would need to be delivered to SD, that will help us appropriately plan. Thanks!

**Comment by JessicaMarine1** [comment]
@anjunainaustin At least 1 week before you want it launched.

**Comment by jfredrickson5** [comment]
Ready for review:
* [Offerings page](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/fast-track/offerings/)
* [Fast Track page](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/fast-track/offerings/fast-track/)

**Comment by jfredrickson5** [comment]
Added external link icon, it's in preview now.

**Comment by JessicaMarine1** [comment]
the PO would like to turn the models into H3 headings so that they appear in the in-page nav menu. Jenn mocked this up:


![Image](https://github.com/GSA/wp2030-microsite/assets/92383362/fb83c5ce-9c44-4ca4-9927-f8142a6fde81)

Could you please do this for the 4 models?

**Comment by jfredrickson5** [comment]
OK, updated the headings.

**Comment by anjunainaustin** [comment]
Looks great!
