### ISSUE TITLE
Re-order offerings landing page (deploy by 7/17)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#268]
- [ ] Re-order [offerings landing page](https://www.gsa.gov/workplace/offerings/) to match this design:

https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?type=design&node-id=2224-583&t=8HQjuIi8yWRVA2jM-0&scaling=scale-down-width&page-id=2224%3A580&starting-point-node-id=2224%3A583&hide-ui=1

- [ ] Update link language for Fast Track offering

**Comment by jfredrickson5** [comment]
Ready for review:
* [Offerings page](https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/fast-track/offerings/)

**Comment by JessicaMarine1** [comment]
QA feedback:
- The copy for Fast Track space (bottom right) on the landing page should read: Choose cost-effective, professionally designed hybrid floor plans that can **meet** an accelerated requirements and design schedule
- The link for federal coworking should read: Learn more about ~~the~~ federal coworking

**Comment by anjunainaustin** [comment]
@JessicaMarine1 I saw the same two things you saw, otherwise looks good to push to prod!

**Comment by jfredrickson5** [comment]
> The link for federal coworking should read: Learn more about the federal coworking

@JessicaMarine1 Should it be "Learn more..." or "Read more..."?

**Comment by JessicaMarine1** [comment]
@jfredrickson5 apologies...it should be "Read more..."

The only thing that needs to change is removing the word "the"

**Comment by JessicaMarine1** [comment]
Approved by PO: https://github.com/GSA/wp2030-microsite/issues/268#issuecomment-1632470936

**Comment by JessicaMarine1** [comment]
7.13.23 Update - per PO, the program needs time to update the floorplans. This is on hold until then.

**Comment by anjunainaustin** [comment]
Can proceed with existing floorplans, thank you for your patience while the program discussed!
