### ISSUE TITLE
Use external link indicator only for non-gsa.gov sites (Release 8/7)

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite#270]
- [ ] Remove the external link icon for any existing links that go to a gsa.gov URL (footer & body copy)

**Comment by mark-meyer** [comment]
@actuallyjenn & @anjunainaustin These changes are up on staging: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/mmeyer/270-gsa-remove-external-links/

**Comment by anjunainaustin** [comment]
Reviewed!
