### ISSUE TITLE
Urgent: Add "WIL is closed" message to site

### ISSUE THREAD

**Issue by anjunainaustin** [GSA/wp2030-microsite#277]
Ryan B. has notified me that WIL is closed today for a private event, and their message on PlaceOS is not working to stem confusion. 

Can you please add a banner (font, placement, and font color is designer's choice based on what would be most alert-worthy) on:
- https://workplace.gsa.gov/ 
- https://workplace.gsa.gov/offerings/ 
- https://workplace.gsa.gov/offerings/innovation-lab/ 

"The Workplace Innovation Lab is closed July 24, 2023 - July 26, 2023 and will not accept reservations. Reservations will resume July 27, 2023."

@JessicaMarine1 filing this as urgent given the number of emails the WIL team is receiving. I have requested from Ryan B. to provide me a list of all other known WIL closures so that I can plan these messages with SD in advance in the future.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa I would use the "Alert" pattern: https://designsystem.digital.gov/components/alert/

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 Ready for QA review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@weiwang-gsa I think these are good to go to `prod`.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 it is deployed to production : https://workplace.gsa.gov/
