### ISSUE TITLE
Remove WIL closure banner (7/27)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#280]
Remove the WIL temporary closure banner on:

- https://workplace.gsa.gov/ 
- https://workplace.gsa.gov/offerings/ 
- https://workplace.gsa.gov/offerings/innovation-lab/

**Comment by weiwang-gsa** [comment]
@JessicaMarine1  this is ready for QA: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@weiwang-gsa this looks good to me! Feel free to push to prod first thing in the morning! Thank you!!

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 Thank you for approving the PR, this is deployed to production: https://workplace.gsa.gov/

**Comment by JessicaMarine1** [comment]
Confirmed banners are removed from `prod`. Moving to Closed.
