### ISSUE TITLE
Add addresses to Federal Coworking page (Release 8/7)

### ISSUE THREAD

**Issue by anjunainaustin** [GSA/wp2030-microsite#281]
The Federal Coworking program has discovered that providing addresses of the coworking locations would help users.

On https://workplace.gsa.gov/offerings/federal-coworking/ there is an image of a map. Please somehow indicate the addresses for each location:

-Philadelphia: 100 S. Independence Mall West, Philadelphia, PA 19106
-Chicago: 230 S. Dearborn St., Chicago, IL 60604
-Kansas City: 2300 Main St., Kansas City, MO 64108
-Denver: Denver Federal Center, Building 41, 1 Denver Federal Center, Main Ave., Denver, CO 80225
-San Francisco: 50 United Nations Plaza, San Francisco, CA 94102
-Tacoma: 1301 A St., Tacoma, WA 98402

**Several changes needed in the `Participate in federal coworking` section**

Design: https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?type=design&node-id=2304-295&t=oku26RgRjKOTdiRJ-0&scaling=min-zoom&page-id=1901%3A402&starting-point-node-id=2304%3A295

Should work on both mobile and desktop.

**Comment by anjunainaustin** [comment]
forgot to ask Program about their hard deadlines, will update issue shortly

**Comment by JessicaMarine1** [comment]
@actuallyjenn Could you please weigh in here on design?

**Comment by anjunainaustin** [comment]
No hard deadline

**Comment by mark-meyer** [comment]
This is up on the staging branch https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/federal-coworking/

[one note, the Figma design has the icon for external sites on the `register your agency`…I've left if off here since we are removing them on the next story. 

@JessicaMarine1 I am not sure who to tag here for QA in @anjunainaustin's absence.

**Comment by JessicaMarine1** [comment]
@anjunainaustin this is ready for your review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/federal-coworking/

**Comment by anjunainaustin** [comment]
Reviewed!
