### ISSUE TITLE
Update based on PBS Commissioner changes

### ISSUE THREAD

**Issue by anjunainaustin** [GSA/wp2030-microsite#299]
Due to Nina Albert's departure from GSA, we need to make the following changes:

- [ ] update https://workplace.gsa.gov/pages/insights/future-work-path-forward/ by adding "Former" before Nina's name
- [ ] replace picture of Nina with https://drive.google.com/file/d/1W1zrJYozmpmfonFegQSMY6eg9Ur0_OSF/view?usp=sharing (Will Powell).

**Comment by weiwang-gsa** [comment]
@anjunainaustin  do you mean adding "Former" before "PBS Commissioner"?
<img width="714" alt="image" src="https://github.com/GSA/wp2030-microsite/assets/119954777/c7863645-ef01-4398-acd5-a89693a30829">

**Comment by anjunainaustin** [comment]
Sorry for confusion, yes please @weiwang-gsa !

**Comment by weiwang-gsa** [comment]
@anjunainaustin this is ready for QA review here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/insights/

If it looks fine, please let us know when you want it to be deployed to production, thank you!

**Comment by anjunainaustin** [comment]
Looks good @weiwang-gsa please push to prod and thank you!

**Comment by weiwang-gsa** [comment]
@anjunainaustin we noticed that on production site(https://workplace.gsa.gov/insights/), the article [Videos: Build a future-ready workforce](https://www.gsa.gov/about-us/events-and-training/gsa-training-programs/fast-overview/archive-of-fast-2023-resources) are link to page not found, we update the video link to https://www.gsa.gov/about-us/events-and-training/gsa-training-programs/fast-overview/archive-of-fast-2023-resources

You can verify this on staging site here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/insights/

If you are ok with this, we will include this change into today's production release as well. Please let us know, thank you!

**Comment by anjunainaustin** [comment]
Great catch and good idea @weiwang-gsa !

**Comment by weiwang-gsa** [comment]
@anjunainaustin thanks for confirmation, just let you know:

-  It is been deployed to production site, you can do final verification here: https://workplace.gsa.gov/insights/
- [release note here](https://github.com/GSA/wp2030-microsite/releases/tag/wp2030-microsite-v15.0)

Once it passed your final verification, please close it as it is been shipped. Thank you so much for all the help!
