### ISSUE TITLE
update external links to reflect new design pattern (part 1)

### ISSUE THREAD

**Issue by actuallyjenn** [GSA/wp2030-microsite#71]
<img width="57" alt="image" src="https://user-images.githubusercontent.com/6501138/217341664-f82b8d68-1ab4-4988-82a8-37ece1a3d017.png">.
New design pattern is needed throughout the workplace site for external links:
- [ ] Use the USWDS 'launch' icon to indicate the link opens an external site
- [ ] External pages should open in the current window
- [ ] Apply new design pattern to **11 places** in the footer:

![Image](https://user-images.githubusercontent.com/92383362/223177006-ec1b6fe7-fb0e-4c47-afb0-3ab09d83f19f.png)

- [ ] Apply new design pattern **1 place** on the [offering landing page](https://workplace.gsa.gov/offerings/):

![Image](https://user-images.githubusercontent.com/92383362/223177735-c51958ec-5e51-46a8-88e1-3eee6aebf353.png)

- [ ] Apply new design pattern to **3 places** on the [Contact page}(https://workplace.gsa.gov/contact/): 

![Image](https://user-images.githubusercontent.com/92383362/223179180-e9dd78e7-e557-4b15-91e3-02302ddaab60.png)

**Comment by lesliel789** [comment]
@actuallyjenn  Getting into the external links issue...
3 of our next 4 planned Insights (to publish next week) are external items. Last week, I drafted some teaser text to provide context and user awareness they would be going to a different gov site (OPM and GSA 18F). Then I remembered our Insights do not have teasers. I updated the headlines/titles to be more descriptive. 

I propose that when the title is clicked, it links directly to the external page and opens in a new window or tab so the user doesn't lose their place in our site. Thoughts on user experience for this? Do you recommend a different solution? 

I asked for OSC perspective as well and Alison K cautioned:
double check that opening in a new target isn't against 21st Century IDEA or any other guidance? I thought we weren't supposed to do that anymore — especially if leaving our site. It inflates "time on page" metrics and bothers people to have many tabs open when they are capable of using the back button if they want to come back to our site.

From my personal perspective as a user, I cannot stand having to reverse back out of a site to get to where I started. But I am just one person :)

**Comment by actuallyjenn** [comment]
@lesliel789 totally hear you on this! I put this card on there because our team was going back and forth on how to handle external links. Alison is correct though - it is best practice that all links, even external ones, open within the current page. Ryan, our content designer, shared this [article explaining how to handle links](https://css-tricks.com/use-target_blank/).

Our team uses the [US Web Design System](https://designsystem.digital.gov/) to guide our design and development. It helps ensure that we meet accessibility standards and web best practices across government. If it's helpful to reference, they have a page on [handling links](https://designsystem.digital.gov/components/link/). In particular, the ["What you should do" section](https://designsystem.digital.gov/components/link/#section_7) has examples of how to provide context for external links through an external link indicator and/or referencing the external site either explicitly or in the text itself - this is how I would recommend the workplace site handle both our existing external sites and upcoming Insights articles.

Let me know if you have any questions!

**Comment by lesliel789** [comment]
Thanks for the resources. I read them both. The comments indicate there is still passion on both sides lol but I understand the charge. How about this: 

- [ ] We will have clear titles (text) that indicate the owner of the content. E.g. OPM's hybrid toolkit.
- [ ] We will not have teaser text / additional sentences on the Insights page.
- [ ] Titles will link directly to external pages and open in the current window.
- [ ] I do not believe we need to indicate the links are to official gov sites do we? We only plan to link to official government sites and if that changes in the future we could revisit. 
- [ ] Let's use a consistent icon to indicate the link opens an external site. Is arrow iconography appropriate? I can see an arrow indicating the user is going external and/or indicating opening in a new window. What, in your view, is the best icon for our purposes?

Thanks!

**Comment by actuallyjenn** [comment]
That all sounds great Leslie! If we have the clear titles / text, I agree, we don't need to indicate that fourth item on your list. 

In terms of icon, this one (called 'launch') is the suggested / recommended that we can implement:
<img width="57" alt="image" src="https://user-images.githubusercontent.com/6501138/217341664-f82b8d68-1ab4-4988-82a8-37ece1a3d017.png">.

**Comment by lesliel789** [comment]
Great thanks! I will copy these decisions into this card's description so it's consolidated and clear. (My teacher, Jessica, gave me that tip!) 
Does this card migrate through the workflow like others since it's a sitewide principle rather than a specific action item?

**Comment by lesliel789** [comment]
NVM ^  I don't think I can edit the top / description.

**Comment by actuallyjenn** [comment]
I can copy it over and update the card to reflect changes that we need to make for external links that already exist on the site, so it'll be reframed as an action that we can then move like the others ones.

**Comment by JessicaMarine1** [comment]
@actuallyjenn Can this issue be closed or are there other external links on the site that need to have this design pattern update?

**Comment by actuallyjenn** [comment]
all of the external links on the site haven't been updated yet so i think we should keep this one open until they all do

**Comment by JessicaMarine1** [comment]
Per Jenn (based on USWDS recommendation), links to anywhere outside workplace should have this new design pattern

**Comment by JessicaMarine1** [comment]
This issue applies the new design pattern to the main pages of the workplace site. Changes to the individual offering and individual insight pages covered by #219

**Comment by JessicaMarine1** [comment]
@actuallyjenn Please review the updated issue and let me know if you agree with the places I've suggested we add this new design pattern. Please note that any changes needed for the individual offering and individual insight pages covered by #219 (TBD)

**Comment by actuallyjenn** [comment]
This looks good to me @JessicaMarine1 - all of the spots have been identified that I could tell!

**Comment by weiwang-gsa** [comment]
@actuallyjenn just double check with you. the launch icon should be inside the link, right? (hover over on the launch icon, it should have hand icon)


![Image](https://user-images.githubusercontent.com/119954777/223773399-bc544680-7b6e-458a-9f2e-56d252cd16b0.png)

**Comment by weiwang-gsa** [comment]
@lesliel789 this ticket is ready for QA, can be reviewed here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@lesliel789 I'm happy to QA this one since I added it.

@weiwang-gsa it all looks good except for the wrapping on the Office of the Inspector General in the footer. Is there a way to make that so that the icon doesn't wrap onto another line?

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 currently it is just list items, it got auto wrapped since text is too long, will take a look tomorrow and see if I can add some layout to it.

**Comment by weiwang-gsa** [comment]
@actuallyjenn we figured out to use USWDS class ="usa-link--external", seems render same look and feel of USWDS site footer.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 looks like there are more external links in insights articles. e.g. NRC + GSA one, should we include them as well? If yes, I will continue work on these next Monday.

**Comment by JessicaMarine1** [comment]
@weiwang-gsa I broke this work up into 2 stories. Any external links on the individual offering pages or insights will be identified and addressed in the other one. Thank you!

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 used the USWDS class for external link, and issue is ready for review here: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/

**Comment by JessicaMarine1** [comment]
@actuallyjenn do you want to look at these as well? I know you had some questions about them previously -- especially on the Contact page?

**Comment by actuallyjenn** [comment]
it looks good, but one thing... noticed that the icon after the insight article titles are a different color? i'd expect them to be black here.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/6501138/224770571-2704d33c-82e5-4e50-bc89-91ff35cfe861.png">

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 actually the same link class is used for all places, but it renders differently in different section, e.g. footer it is white , article content is link default color, here we let the link display without underline, but launch icon still keep the same color as default link color like normal link in article. If you want here to be black, I can add inline style to overwrite its default color and make it black.

**Comment by JessicaMarine1** [comment]
@actuallyjenn ^^^

**Comment by JessicaMarine1** [comment]
Looks good. Moving to done!
